kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: softhsm-data-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: standard
spec:
   accessModes:
     - ReadWriteMany
   resources:
     requests:
       storage: 10Gi
